name = "portfolio"
main = "worker/index.js"
compatibility_date = "2025-05-01"

routes = [
  { pattern = "kaushikrb.com", custom_domain = true },
  { pattern = "www.kaushikrb.com", custom_domain = true },
]

[assets]
directory = "./src"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true
